const PUBLIC_WUSHU_COPY_REPLACEMENTS = [
  [/\bNew England Wushu Summer Camp\b/g, 'Summer Wushu Week'],
  [/\bWushu Summer Camp\b/g, 'Summer Wushu Week'],
  [/\bCompetition Team Boot Camp\b/g, 'Competition Team Wushu Week'],
  [/\bCompetition Boot Camp\b/g, 'Competition Wushu Week'],
  [/\bcompetition team boot camp\b/g, 'competition team wushu week'],
  [/\bcompetition boot camp\b/g, 'competition wushu week'],
  [/\bBoot Camp\b/g, 'Competition Wushu Week'],
  [/\bBoot camp\b/g, 'Competition Wushu Week'],
  [/\bboot camp\b/g, 'competition wushu week'],
  [/\bGeneral Camp\b/g, 'General Summer Wushu Week'],
  [/\bgeneral camp\b/g, 'general summer wushu week'],
  [/\bOvernight Camp\b/g, 'Overnight Wushu Week'],
  [/\bovernight camp\b/g, 'overnight wushu week'],
  [/\bSummer Day Camp\b/g, 'Summer Wushu Week'],
  [/\bSummer Camp\b/g, 'Summer Wushu Week'],
  [/\bsummer camp\b/g, 'summer wushu week'],
  [/\bDay Camp\b/g, 'Summer Wushu Week'],
  [/\bday camp\b/g, 'summer wushu week'],
  [/\bcampers\b/g, 'students'],
  [/\bCampers\b/g, 'Students'],
  [/\bcamper\b/g, 'student'],
  [/\bCamper\b/g, 'Student'],
  [/\bcamp days\b/g, 'summer wushu week days'],
  [/\bCamp days\b/g, 'Summer Wushu Week days'],
  [/\bcamp day\b/g, 'summer wushu week day'],
  [/\bCamp day\b/g, 'Summer Wushu Week day'],
  [/\bcamp weeks\b/g, 'summer wushu weeks'],
  [/\bCamp weeks\b/g, 'Summer Wushu Week weeks'],
  [/\bcamp week\b/g, 'summer wushu week'],
  [/\bCamp week\b/g, 'Summer Wushu Week'],
  [/\bcamp tuition\b/g, 'program tuition'],
  [/\bCamp tuition\b/g, 'Program tuition'],
  [/\bcamp discount\b/g, 'program discount'],
  [/\bCamp discount\b/g, 'Program discount'],
  [/\bcamp updates\b/g, 'program updates'],
  [/\bCamp updates\b/g, 'Program updates'],
  [/\bcamp location\b/g, 'program location'],
  [/\bCamp location\b/g, 'Program location'],
  [/\bcamp type\b/g, 'program type'],
  [/\bCamp type\b/g, 'Program type'],
  [/\bcamp path\b/g, 'wushu program path'],
  [/\bCamp path\b/g, 'Wushu program path'],
  [/\bcamp life\b/g, 'wushu week life'],
  [/\bCamp life\b/g, 'Wushu week life'],
  [/\bcamp house\b/g, 'lodging house'],
  [/\bCamp House\b/g, 'Lodging House'],
  [/\bcamp\b/g, 'wushu program'],
  [/\bCamp\b/g, 'Wushu Program'],
]

export function publicWushuCopy(value) {
  if (typeof value !== 'string') {
    return value
  }
  return PUBLIC_WUSHU_COPY_REPLACEMENTS.reduce((copy, [pattern, replacement]) => copy.replace(pattern, replacement), value)
}
